name: Pagoda Fitness
favicon: null
layout_spectrum: 0.19858007552102208
typography_spectrum: 0.37220223317854106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6832969933748245
  lightness: 0.7953841967973858
  saturation: 0.8828695600386709
  rhythmicContrast: 0.15353778237476945
purpose: []
